package com.example.xuxiao415.mycourse.MyDataBase;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.xuxiao415.mycourse.MyDataBase.MyCurriculumTable;
import com.example.xuxiao415.mycourse.MyDataBase.UserInfo;

import com.example.xuxiao415.mycourse.MyDataBase.MyCurriculumTableDao;
import com.example.xuxiao415.mycourse.MyDataBase.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myCurriculumTableDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final MyCurriculumTableDao myCurriculumTableDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myCurriculumTableDaoConfig = daoConfigMap.get(MyCurriculumTableDao.class).clone();
        myCurriculumTableDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        myCurriculumTableDao = new MyCurriculumTableDao(myCurriculumTableDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(MyCurriculumTable.class, myCurriculumTableDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        myCurriculumTableDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public MyCurriculumTableDao getMyCurriculumTableDao() {
        return myCurriculumTableDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
